myNextApp:
  component: "@sls-next/serverless-component@latest"
  inputs:
    bucketName: "examadda-s3"
    memory: 1024
    timeout: 10
    domain: # optional custom domain object if you use Route53 etc
      domainName: examadda.org
      hostedZoneId: ZXXXXXXXX
