myNextApp:
  component: "@sls-next/serverless-component@latest"
  inputs:
    bucketName: "post-examadda"
    memory: 1024
    timeout: 10
    cloudfront:
      defaults:
        ttl: 86400
    domain:   # enable if you have Route53 hosted zone
      domainName: examadda.org
      hostedZoneId: ZXXXXXXXXXXXX